### PR TITLE
Correctly render Skeletons in a FormRow

### LINKED ISSUE #382: Skeletons are not rendered properly in a FormRow
### Bricks version 📦
1.0.3

### Describe the bug 🔍
When using a skeleton in combination with the form row (ie: `<FormRow label={<Skeleton.Text baseWidth={70} lines={1} />} field={<Skeleton.Rect width={'100%'} />} />`. You are shown a label skeleton with minimal width.

### Expected behavior ✨
Nothing more than `<FormRow label={<Skeleton.Text baseWidth={70} lines={1} />} field={<Skeleton.Rect width={'100%'} />} />` should be needed to render a formrow skeleron

### PR DESCRIPTION
**Pull request by hborghols**
### This PR:

resolves #382 

This renders Skeletons in the `FormRow` the same as before the introduction of the `badge` prop.

**Bugfixes/Changed internals** 🎈
- Skeleton now renders properly in the label field of a `FormRow` again.

**Checklist** 🛡
- [x] I have exported my addition from `src/index.ts` (check if not applicable).
- [x] Appropriate tests have been added for my functionality (check if not applicable).
- [x] A designer has seen and approved my changes (tag `@LuukHorsmans` or `@RianneSchaekens` for a design review when applicable).
- [x] I have tested my addition in all supported browsers and for responsiveness (Chrome, Firefox, Safari, Edge, IE11 and mobile browsers).
- [x] Appropriate documentation has been written (check if not applicable).

### CODE REVIEW

File: src/components/FormRow/story.tsx [hunk 1]
```diff
@@ -1,3 +1,4 @@
+// tslint:disable:max-file-line-count
```
Comment (CarloPalinckx) [inline src/components/FormRow/story.tsx]: This line is no longer necessary once you rebase onto master.

Comment (hborghols) [reply src/components/FormRow/story.tsx]: Duh :D
