### PR TITLE
Added min-width to fix rendering issue in firefox

### LINKED ISSUE #310: TextField suffix is not formatted correctly for small widths in Firefox
### Bricks version 📦
0.9.1

### Describe the bug 🔍
In Firefox the suffix of `TextField` is not rendered correctly when the textfield has a small width.

### To Reproduce 💥
1. Make a `TextField` with suffix
2. reduce the width of the textfield (for example by reducing width in storybook)

### Screenshots 📸
screenshot 2019-01-10 at 15 04 18

### Context👨‍💻
 - Device: MBP
 - OS: OSX mojave
 - Browser Firefox Dev Edition
 - Browser version 65.0b5

### PR DESCRIPTION
**Pull request by Dreamdealer**
### This PR:

resolves #310

**Breaking changes** 🔥
- None

**Backwards compatible additions** ✨
- None

**Bugfixes/Changed internals** 🎈
- Added a min-width to the input field. Firefox has an internal/default minimal width that caused this issue. By setting it to a much lower value the issue is resolved.

**Checklist** 🛡
- [x] I have exported my addition from `src/index.ts` (check if not applicable).
- [x] Appropriate tests have been added for my functionality (check if not applicable).
- [x] A designer has seen and approved my changes (tag `@LuukHorsmans` for a design review when applicable).
- [x] I have tested my addition in all supported browsers and for responsiveness (Chrome, Firefox, Safari, Edge, IE11 and mobile browsers).

### CODE REVIEW

File: src/components/TextField/style.tsx [hunk 1]
```diff
@@ -58,6 +58,7 @@ const StyledInput = withProps<InputProps, HTMLInputElement>(styled.input)`
     padding: 6px 12px;
     line-height: 1.572;
     outline: none;
+    min-width: 10px;
```
Comment (CarloPalinckx) [inline src/components/TextField/style.tsx]: Could this be a step of `12px`? 🤓

Comment (Dreamdealer) [reply src/components/TextField/style.tsx]: Haha that doesn't matter at all, but for OCD's sake I'll change it 👍
