### PR TITLE
Solved currency input bugs

### LINKED ISSUE #186: Textfield input (currency)
### Bricks version 📦
0.1.0

### Describe the bug 🔍
When the value of the currency is edited, the cursor will be moved to the end of the input. This is likely caused by the regex that removes the dot in large numbers, this behaviour is also caused by filling in a character. 

### To Reproduce 💥
1. Go to Bricks > Textfield > currency
2. Fill in a character anywhere (not the end) in the string

1. Go to Bricks > Textfield > currency
2. fill the input with `100000`
3. blur the input
4. add a number to the string. 

### Expected behavior ✨
The cursor should stay at the right position. 
Another solution could be to remove the dot(s) on focus.

### PR DESCRIPTION
**Pull request by nicokoelewijn**
### This PR:

proposed release: `minor`
resolves #186 

**Checklist** 🛡
- [x] I have exported my addition from `src/index.ts` (check if not applicable)

**Changes** 🌀
- Cursor no longer jumps to end when a NaN-character is pressed. 
- Input can now be disabled
- When the currency input is empty on blur, the value will be set to 0 instead of reverting to the last value.

**Breaking changes 🔥**

- `backgroundColor` properties in `theme.TextField` changed to `background`.

### CODE REVIEW

File: src/components/TextField/formatters/withCurrencyFormatting/index.tsx [hunk 1]
```diff
@@ -105,13 +101,32 @@ const withCurrencyFormatting = (Wrapped: ComponentType<TextFieldPropsType>): Com
...
+
+            this.setState({ value: this.parse('in', value) }, () => {
+                target.selectionEnd = this.state.inputLength === newInputLength ? selectionStart : selectionStart - 1;
+            });
         };
 
         private handleBlur = (): void => {
-            this.setState({ value: this.format(this.state.value) });
+            if (this.state.value.length !== 0) {
+                return this.setState({ value: this.format(this.state.value) });
```
Comment (CarloPalinckx) [inline src/components/TextField/formatters/withCurrencyFormatting/index.tsx]: This return seems a bit misplaced. If the types of setState would change to return something builds would break, prefer an if/else here

File: src/components/TextField/formatters/withCurrencyFormatting/index.tsx [hunk 2]
```diff
@@ -105,13 +101,32 @@ const withCurrencyFormatting = (Wrapped: ComponentType<TextFieldPropsType>): Com
...
+            }
```
Comment (CarloPalinckx) [inline src/components/TextField/formatters/withCurrencyFormatting/index.tsx]: Nit: newline

File: src/components/TextField/style.tsx [hunk 3]
```diff
@@ -31,29 +31,51 @@ type TextFieldThemeType = {
         borderColor: string;
         boxShadow: string;
     };
+    disabled: {
+        color: string;
+        background: string;
+    };
+};
+
+type affixProps = {
```
Comment (CarloPalinckx) [inline src/components/TextField/style.tsx]: Types and Classes should be uppercase

File: src/components/TextField/style.tsx [hunk 4]
```diff
@@ -31,29 +31,51 @@ type TextFieldThemeType = {
...
 `;
 
-const StyledAffixWrapper = styled.div`
+const StyledAffixWrapper = withProps<affixProps, HTMLDivElement>(styled.div)`
     display: flex;
     padding: 0 12px;
     user-select: none;
-    color: ${({ theme }): string => theme.TextField.idle.affix.color};
-    background-color: ${({ theme }): string => theme.TextField.idle.affix.backgroundColor};
+
```
Comment (CarloPalinckx) [inline src/components/TextField/style.tsx]: Nit: newline

File: src/components/TextField/index.tsx [hunk 5]
```diff
@@ -60,33 +64,33 @@ class TextField extends Component<PropsType, StateType> {
...
 
-        if (this.props.onBlur !== undefined) {
-            this.props.onBlur();
-        }
+        if (this.props.onBlur !== undefined) this.props.onBlur();
     };
 
     public onChange = (event: ChangeEvent<HTMLInputElement>): void => {
-        this.props.onChange(event.target.value);
+        this.props.onChange(event.target.value, event);
```
Comment (CarloPalinckx) [inline src/components/TextField/index.tsx]: This should probably check this.props.disabled. It shouldn't fire the callback once disabled. Check Toggle for similar behaviour.

File: src/components/TextField/test.tsx [hunk 6]
```diff
@@ -11,6 +11,14 @@ describe('TextField', () => {
         expect(component.find(StyledWrapper).prop('active')).toBe(false);
     });
 
+    it('should render a disabled state', () => {
+        const component = mountWithTheme(
+            <TextField value="" disabled suffix={'$'} name="firstName" onChange={jest.fn()} />,
+        );
+
+        expect(component.find(StyledWrapper).prop('active')).toBe(false);
+    });
```
Comment (CarloPalinckx) [inline src/components/TextField/test.tsx]: Maybe you could add a test case to check if the onChange isn't fired when disabled.
