### PR TITLE
Removed checkbox class

### LINKED ISSUE #272: Checkbox offset
### Bricks version 📦
0.6.3

### Describe the bug 🔍
Checkboxes in the FormRow have an offset. This is caused by the checkbox class. 
This  can be solved by implementing the Separate component and removing the checkbox class.

### To Reproduce 💥
Check the offset of the checkbox in a FormRow

### Expected behavior ✨
there shouldn't be an offset on the checkbox. 

### Screenshots 📸
screenshot 2018-12-03 at 15 59 59

### Context👨‍💻
 - Every context

### PR DESCRIPTION
**Pull request by nicokoelewijn**
### This PR:

resolves #272 

proposed release: `patch`

**Checklist** 🛡
- [x] I have exported my addition from `src/index.ts` (check if not applicable)
- [x] Appropriate tests have been added for my functionality (check if not applicable)
- [x] A designer has seen and approved my changes (check if not applicable)
- [x] I have tested my addition in all supported browsers and for responsiveness (Chrome, Firefox, Safari, Edge, IE11 and mobile browsers)

**Changes** 🌀
- Implements Separated component in FormRow

**Removes** 👋
- Depracted `.checkbox` class in FormRow and therefore it's css

**Breaking** 🔥
- Removed .checkbox classname and styling

### CODE REVIEW

**Comment by hborghols** [comment]
The Separate component is intended for grouping things so the way you used it here is not it's use case. You can just use a regular old Box to give the checkbox it's top margin. Also: I would see this as a breaking change because it breaks the positioning of all checkboxes in forms currently in use.

File: src/components/FormRow/story.tsx [hunk 1]
```diff
@@ -9,6 +9,7 @@ import Box from '../Box';
 import TextField from '../TextField';
 import Toggle from '../Toggle';
 import trbl from '../../utility/trbl';
+import Separated from '../Separated';
```
Comment (hborghols) [inline src/components/FormRow/story.tsx]: You don't need this anymore
