### PR TITLE
removed onFocus- onBlurCapture from wrapper to prevent double focus

### LINKED ISSUE #256: Multiple onBlur & onFocus calls on TextField
### Bricks version 📦
0.6.2

### Describe the bug 🔍
The `StyledWrapper` captures the blur and focus events and executes the onBlur and onFocus props, while these are already called on the input. So it results in multiple calls. The onFocus is even called a third time due to the onClickCapture.

The good thing about the click capture is that even when you click on a prefix or suffix, the field is focussed. The rest seems unnecessary.

### To Reproduce 💥
1. Go to story of TextField and add a onBlur and onFocus with a console log or something
2. Focus and blur and behold the console.

### Expected behavior ✨
I would expect it to call the onBlur and onFocus once per event. But I would also expect the field to focus when clicking on a prefix. So I would like to suggest to remove the `onBlurCapture` and `onFocusCapture`, but keep the `onClickCapture` to force a focus on the input.

### PR DESCRIPTION
**Pull request by nicokoelewijn**
### This PR:

removed onFocus- onBlurCapture from wrapper to prevent double focus.
resolves #256  

proposed release: `patch`

**Checklist** 🛡
- [x] I have exported my addition from `src/index.ts` (check if not applicable)
- [x] Appropriate tests have been added for my functionality (check if not applicable)
- [x] A designer has seen and approved my changes (check if not applicable)
- [x] I have tested my addition in all supported browsers and for responsiveness (Chrome, Firefox, Safari, Edge, IE11 and mobile browsers)

**Changes** 🌀
- removed onFocus- onBlurCapture from wrapper to prevent double focus

### CODE REVIEW

File: src/components/TextField/index.tsx [hunk 1]
```diff
@@ -64,12 +63,9 @@ class TextField extends Component<PropsType, StateType> {
                     focus={this.state.focus}
                     disabled={this.props.disabled}
                     severity={this.props.feedback ? this.props.feedback.severity : 'success'}
-                    onFocusCapture={this.handleFocus}
-                    onBlurCapture={this.handleBlur}
-                    onClick={this.handleFocus}
                 >
                     {this.props.prefix && (
-                        <StyledAffixWrapper disabled={this.props.disabled}>
+                        <StyledAffixWrapper onClick={this.handleFocus} disabled={this.props.disabled}>
```
Comment (woutsluiter) [inline src/components/TextField/index.tsx]: The onFocus is still called twice when clicking on a prefix. I think you need to move the `this.inputRef.focus()` in `handleFocus` to a separate `forceFocus` and pass that here.

File: src/components/TextField/test.tsx [hunk 2]
```diff
@@ -36,6 +36,14 @@ describe('TextField', () => {
         expect(component.find(StyledWrapper).prop('focus')).toBe(true);
     });
 
+    it('should render an active state when focussed by clicking an affix', () => {
```
Comment (woutsluiter) [inline src/components/TextField/test.tsx]: nit: I think this should be 'focus'
