### PR TITLE
changed order of Textfield stories and removed focus on disabled bug

### LINKED ISSUE #237: TextField renders a "focus border" when disabled
### Bricks version 📦
v0.6.0

### Describe the bug 🔍
A clear and concise description of what the bug is. Subsequently, you cant blur the field afterwards.

### To Reproduce 💥
1. Render the TextField component with prop "disabled" set to true
2. Click the field

### Expected behavior ✨
A TextField component still applies a focus border when clicked

### Screenshots 📸
screenshot 2018-10-26 at 07 43 27

### PR DESCRIPTION
**Pull request by nicokoelewijn**
### This PR:

Changed order of Textfield stories and removed focus on disabled bug.
resolves #237 

proposed release: `patch`

**Checklist** 🛡
- [x] I have exported my addition from `src/index.ts` (check if not applicable)
- [x] Appropriate tests have been added for my functionality (check if not applicable)

**Changes** 🌀
- Changed order of Textfield stories
- Removed focus on disabled (bug)

### CODE REVIEW

File: src/components/TextField/story.tsx [hunk 1]
```diff
@@ -6,17 +6,22 @@ import SeverityType from '../../types/SeverityType';
 
 type DemoPropsType = {
     withFeedback: boolean;
+    hoc?: string;
```
Comment (hborghols) [inline src/components/TextField/story.tsx]: Maybe you can change the name of this prop to formatter/formatting to show the intention rather than the implementation detail.

File: src/components/TextField/story.tsx [hunk 2]
```diff
@@ -6,17 +6,22 @@ import SeverityType from '../../types/SeverityType';
...
+class Demo extends Component<DemoPropsType, DemoStateType> {
     public ref: HTMLInputElement;
 
     public constructor(props: DemoPropsType) {
         super(props);
 
-        this.state = {
-            value: '',
-        };
+        this.state = { numVal: 10.0, strVal: '' };
```
Comment (hborghols) [inline src/components/TextField/story.tsx]: What is this, PHP? ;).

Comment (nicokoelewijn) [reply src/components/TextField/story.tsx]: so, you prefer numberValue and stringValue?

File: src/components/TextField/story.tsx [hunk 3]
```diff
@@ -6,17 +6,22 @@ import SeverityType from '../../types/SeverityType';
...
     }
 
     public componentDidMount(): void {
```
Comment (hborghols) [inline src/components/TextField/story.tsx]: I know it wasn't added in this PR but this button doesn't work for me. It disappears after being visible very briefly.

File: src/components/TextField/story.tsx (hunk 1 above)
Comment (nicokoelewijn) [reply src/components/TextField/story.tsx]: shure, nice catch

File: src/components/TextField/story.tsx (hunk 3 above)
Comment (hborghols) [reply src/components/TextField/story.tsx]: You can check if there's an easy fix otherwise create a new bug I'd say

File: src/components/TextField/story.tsx (hunk 2 above)
Comment (hborghols) [reply src/components/TextField/story.tsx]: Yeah I do, I'm not suuuuper against these though. I had to think of php's strval function.

File: src/components/TextField/story.tsx (hunk 3 above)
Comment (nicokoelewijn) [reply src/components/TextField/story.tsx]: not really shure why it's here in the first place, i ditched it
